trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@2
  displayName: 'Get secret from Key Vault'
  inputs:
    azureSubscription: 'DeployTraineeSkillsSolution'
    KeyVaultName: 'kv-trainee-skills-dev'
    SecretsFilter: '*'

- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'DeployTraineeSkillsSolution'
    ServerName: 'sqlsrv-trainee-skills-tst.database.windows.net'
    DatabaseName: 'sqldb-trainee-skills-tst'
    SqlUsername: '$(sqldb-username)'
    SqlPassword: '$(sqldb-password)'
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: 'testfile.sql'
    IpDetectionMethod: 'AutoDetect'