trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@2
  displayName: 'Get secrets from Key Vault'
  inputs:
    azureSubscription: 'DeployTraineeSkillsSolution'
    KeyVaultName: 'kv-trainee-skills-dev'
    SecretsFilter: 'sqldb-username, sqldb-password'

- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'DeployTraineeSkillsSolution'
    ServerName: 'sqlsrv-trainee-skills-tst.mysql.database.windows.net'
    DatabaseName: 'sqldb-trainee-skills-tst'
    SqlUsername: '$(sqldb-username)'
    SqlPassword: '$(sqldb-password)'
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: '$(Build.SourcesDirectory)/create-tables-for-development.sql'
    IpDetectionMethod: 'AutoDetect'