trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- task: AzureKeyVault@2
  displayName: 'Get secrets from Key Vault'
  inputs:
    azureSubscription: 'DeployTraineeSkillsSolution'
    KeyVaultName: 'kv-trainee-skills-tst'
    SecretsFilter: 'sqldb-username, sqldb-password'

- task: SqlAzureDacpacDeployment@1
  displayName: 'Create or update stored procedures and table trigger'
  inputs:
    azureSubscription: 'DeployTraineeSkillsSolution'
    AuthenticationType: 'server'
    ServerName: 'sqlsrv-trainee-skills-tst.database.windows.net'
    DatabaseName: 'sqldb-trainee-skills-tst'
    SqlUsername: '$(sqldb-username)'
    SqlPassword: '$(sqldb-password)'
    deployType: 'SqlTask'
    SqlFile: '$(Build.SourcesDirectory)/update-stored-procedures-and-table-trigger.sql'
    IpDetectionMethod: 'AutoDetect'