trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureFunctionApp@1
  displayName: 'Deploy logic app workflows'
  inputs:
     azureSubscription: 'MyServiceConnection'
     appType: 'functionAppLinux'
     appName: 'la-msf-dev'
     package: 'MyBuildArtifact.zip'
     deploymentMethod: 'zipDeploy'